-- CITIES
INSERT INTO city VALUES ('1', 'Kampala', 'Uganda');
INSERT INTO city VALUES ('2', 'Jinja', 'Uganda');
INSERT INTO city VALUES ('3', 'Mbarara', 'Uganda');
INSERT INTO city VALUES ('4', 'Gulu', 'Uganda');
INSERT INTO city VALUES ('5', 'Kotido', 'Uganda');
INSERT INTO city VALUES ('6', 'Wakiso', 'Uganda');
INSERT INTO city VALUES ('7', 'Fort Portal', 'Uganda');
INSERT INTO city VALUES ('8', 'Nairobi', 'Kenya');
INSERT INTO city VALUES ('9', 'Eldoret', 'Kenya');
INSERT INTO city VALUES ('10', 'Lamu', 'Kenya');
INSERT INTO city VALUES ('11', 'Kakamega', 'Kenya');
INSERT INTO city VALUES ('12', 'Kigali', 'Rwanda');
INSERT INTO city VALUES ('13', 'Bujumbura', 'Burundi');
INSERT INTO city VALUES ('14', 'Lagos', 'Nigeria');
INSERT INTO city VALUES ('15', 'Lusaka', 'Zambia');
INSERT INTO city VALUES ('16', 'Dar es Salaam', 'Tanzania');
INSERT INTO city VALUES ('17', 'Mombasa', 'Kenya');
INSERT INTO city VALUES ('18', 'Maiduguri', 'Nigeria');
INSERT INTO city VALUES ('19', 'Abuja', 'Nigeria');
INSERT INTO city VALUES ('20', 'Johannesburg', 'South Africa');